In [4]:
!pip3 install torch torchvision

    100% |████████████████████████████████| 519.5MB 28kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x58a2c000 @  0x7f7c038ad1c4 0x46d6a4 0x5fcbcc 0x4c494d 0x54f3c4 0x553aaf 0x54e4c8 0x54f4f6 0x553aaf 0x54efc1 0x54f24d 0x553aaf 0x54efc1 0x54f24d 0x553aaf 0x54efc1 0x54f24d 0x551ee0 0x54e4c8 0x54f4f6 0x553aaf 0x54efc1 0x54f24d 0x551ee0 0x54efc1 0x54f24d 0x551ee0 0x54e4c8 0x54f4f6 0x553aaf 0x54e4c8
    100% |████████████████████████████████| 61kB 1.6MB/s 
    100% |████████████████████████████████| 2.0MB 2.4MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0


In [0]:
import numpy as np

In [0]:
arr = np.array([[1,2], [3,4]])

In [0]:
import torch

In [9]:
torch.tensor(arr)

tensor([[1, 2],
        [3, 4]])

In [10]:
torch.ones([2,2])

tensor([[1., 1.],
        [1., 1.]])

In [11]:
torch.rand(2,2)

tensor([[0.5097, 0.8112],
        [0.3059, 0.0825]])

In [0]:
#seeds

In [13]:
torch.manual_seed(3)

In [16]:
torch.rand(2,2)

tensor([[0.0043, 0.1056],
        [0.2858, 0.0270]])

In [18]:
torch.manual_seed(3)
torch.rand(2,2)

tensor([[0.0043, 0.1056],
        [0.2858, 0.0270]])

In [0]:
# seed for gpu

In [20]:
if torch.cuda.is_available():
  print("Is available!")
  torch.cuda.manual_seed_all(0)

Is available!


In [0]:
# numpy and torch bridge

In [0]:
np_array = np.ones(2)

In [0]:
torch_tensor = torch.from_numpy(np_array)

In [25]:
torch_tensor

tensor([1., 1.], dtype=torch.float64)

In [26]:
np_array_err = np.ones((2,2), dtype=np.int8)
torch.from_numpy(np_array_err)

TypeError: ignored

In [0]:
# conversion supports only double float int64 int32 and uint8

In [0]:
# torch to numpy

In [0]:
torch_tensor = torch.ones(2,2)

In [30]:
torch_tensor.numpy()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [0]:
# tensors from cpu to gpu and vice versa

In [0]:
tensor_cpu = torch.ones(2,2)

In [33]:
#to GPU
tensor_cpu.cuda()

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [35]:
# To CPU back
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

In [0]:
# tensor operations

In [0]:
a = torch.ones(2,2)

In [38]:
a.view(4)

tensor([1., 1., 1., 1.])

In [0]:
b = a

In [41]:
a + b

tensor([[2., 2.],
        [2., 2.]])

In [42]:
torch.add(a, b)

tensor([[2., 2.],
        [2., 2.]])

In [0]:
# inplace operations ...these have _

In [44]:
b.add_(a)

tensor([[2., 2.],
        [2., 2.]])

In [45]:
b

tensor([[2., 2.],
        [2., 2.]])

In [47]:
b.sub_(a)

tensor([[0., 0.],
        [0., 0.]])

In [50]:
b

tensor([[0., 0.],
        [0., 0.]])

In [0]:
 # same goes for multiplication

In [0]:
a = torch.tensor([1,2,3,4,5,6,7,8,9,10], dtype=torch.float)

In [56]:
a.mean(dim=0)

tensor(5.5000)

In [0]:
a = torch.tensor([[1,2,3,4,5,6,7,8,9,10], [1,2,3,4,5,6,7,8,9,10]], dtype=torch.float) 

In [60]:
a.mean(dim=0)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
#variables

In [0]:
from torch.autograd import Variable

In [0]:
a =  Variable(torch.ones(2,2), requires_grad=True)

In [65]:
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [0]:
b =  Variable(torch.ones(2,2), requires_grad=True)

In [67]:
print(a + b)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)


In [0]:
# what is requires_grad?

In [0]:
x = Variable(torch.ones(2), requires_grad=True)

In [0]:
y = 5 * (x + 1) ** 2

In [72]:
y

tensor([20., 20.], grad_fn=<MulBackward>)

In [0]:
o = (1/2) * torch.sum(y)

In [75]:
o

tensor(20., grad_fn=<MulBackward>)

In [0]:
o.backward()

backward works only on scalars

In [77]:
x.grad

tensor([10., 10.])

In [0]:
# Linear Regression